const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('operant', {
  config: () => ipcRenderer.invoke('config'),
  setConfig: patch => ipcRenderer.invoke('config:set', patch),
  defaults: () => ipcRenderer.invoke('config:defaults'),
  createPty: opts => ipcRenderer.invoke('pty:create', opts),
  writePty: (id, data) => ipcRenderer.send('pty:write', { id, data }),
  resizePty: (id, cols, rows) => ipcRenderer.send('pty:resize', { id, cols, rows }),
  killPty: id => ipcRenderer.send('pty:kill', { id }),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  openConfig: () => ipcRenderer.send('open-config'),
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  newWindow: () => ipcRenderer.send('win:new'),
  windowFocused: () => ipcRenderer.invoke('win:focused'),
  notify: n => ipcRenderer.send('notify', n),
  devtools: () => ipcRenderer.send('devtools'),
  version: () => ipcRenderer.invoke('app:version'),
  startupFolder: () => ipcRenderer.invoke('startup-folder'),
  checkUpdate: () => ipcRenderer.send('update:check'),
  installUpdate: () => ipcRenderer.send('update:install'),
  updateState: () => ipcRenderer.invoke('update:state'),
  openReleases: () => ipcRenderer.send('open-releases'),
  openLink: url => ipcRenderer.send('open-link', url),
  listDir: (dir, hidden) => ipcRenderer.invoke('fs:list', { dir, hidden }),
  isDir: p => ipcRenderer.invoke('fs:is-dir', p),
  openPath: p => ipcRenderer.send('fs:open', p),
  reveal: p => ipcRenderer.send('fs:reveal', p),
  openInIde: p => ipcRenderer.invoke('ide:open', p),
  codegraphVersion: () => ipcRenderer.invoke('codegraph:version'),
  mediaState: () => ipcRenderer.invoke('media:state'),
  media: cmd => ipcRenderer.send('media:command', cmd),
  usageSummary: () => ipcRenderer.invoke('usage:summary'),
  usageSeries: range => ipcRenderer.invoke('usage:series', range),
  on: (ch, fn) => ipcRenderer.on(ch, (_e, d) => fn(d)),
});
