// Generates docs/architecture.md (module map) and docs/dependencies.md (dependency report) from the repo itself.
// Run with `npm run docs`. The builders are pure; files are written only when this is run directly.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIRS = ['bin', 'renderer', 'platform', 'hooks'];
const CODE = /\.(js|mjs|cjs|sh|cmd)$/;

function leadingComment(src) {
  const lines = src.replace(/^﻿/, '').split(/\r?\n/);
  let i = 0;
  while (i < lines.length && /^(#!|\(function\s*\(\)\s*\{|@echo off|setlocal)/i.test(lines[i].trim())) i++;
  const out = [];
  for (; i < lines.length; i++) {
    const m = /^\s*(?:\/\/|#|::|REM\s)\s?(.*)$/i.exec(lines[i]);
    if (m) out.push(m[1].trim());
    else if (!lines[i].trim() && !out.length) continue;
    else break;
  }
  const text = out.join(' ').replace(/\s+/g, ' ').trim();
  if (!text) return '';
  const first = /^(.+?[.:;])(\s|$)/.exec(text);
  let s = first && first[1].length > 25 ? first[1] : text;
  if (s.length > 220) s = s.slice(0, 217).replace(/\s+\S*$/, '') + '...';
  return s.replace(/[.:;]$/, '.').replace(/\|/g, '\\|');
}

function fallback(src) {
  const reqs = [...new Set([...src.matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g)].map((m) => m[1]))];
  const local = reqs.filter((r) => r.startsWith('.')).map((r) => path.basename(r));
  const exp = /module\.exports\s*=\s*\{([^}]*)\}/.exec(src);
  const names = exp ? exp[1].split(',').map((x) => x.split(':')[0].trim()).filter(Boolean).slice(0, 6) : [];
  const parts = [];
  if (names.length) parts.push(`exports ${names.join(', ')}`);
  if (local.length) parts.push(`uses ${local.slice(0, 6).join(', ')}`);
  else if (reqs.length) parts.push(`requires ${reqs.slice(0, 4).join(', ')}`);
  return parts.length ? parts.join('; ') + '.' : 'Windows batch launcher.';
}

function describe(file) {
  const src = fs.readFileSync(file, 'utf8');
  return leadingComment(src) || fallback(src);
}

function listFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && CODE.test(e.name))
    .map((e) => e.name).sort();
}

function buildArchitecture(root = ROOT) {
  const sections = [['Top level', '', listFiles(root)], ...DIRS.map((d) => [d + '/', d, listFiles(path.join(root, d))])];
  let out = "# Architecture\n\nModule map generated by `npm run docs` from each file's leading comment. Do not edit by hand.\n";
  for (const [title, dir, files] of sections) {
    if (!files.length) continue;
    out += `\n## ${title}\n\n| File | Purpose |\n| --- | --- |\n`;
    for (const f of files) out += `| \`${dir ? dir + '/' : ''}${f}\` | ${describe(path.join(root, dir, f))} |\n`;
  }
  return out;
}

function lockPackages(root) {
  const p = path.join(root, 'package-lock.json');
  if (!fs.existsSync(p)) return {};
  return JSON.parse(fs.readFileSync(p, 'utf8')).packages || {};
}

function buildDependencies(root = ROOT) {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const packages = lockPackages(root);
  const versions = new Map();
  let total = 0;
  for (const [key, val] of Object.entries(packages)) {
    if (!key) continue;
    total++;
    const name = key.slice(key.lastIndexOf('node_modules/') + 'node_modules/'.length);
    if (!versions.has(name)) versions.set(name, new Map());
    const v = versions.get(name);
    const ver = val.version || '?';
    v.set(ver, (v.get(ver) || 0) + 1);
  }
  const direct = new Set([...Object.keys(pkg.dependencies || {}), ...Object.keys(pkg.devDependencies || {}), ...Object.keys(pkg.optionalDependencies || {})]);
  const transitive = Math.max(0, total - direct.size);
  const table = (obj) => {
    const names = Object.keys(obj || {}).sort();
    if (!names.length) return '_None._\n';
    let t = '| Package | Range | Locked |\n| --- | --- | --- |\n';
    for (const n of names) {
      const locked = packages['node_modules/' + n] ? packages['node_modules/' + n].version : 'not in lockfile';
      t += `| \`${n}\` | \`${obj[n]}\` | ${locked} |\n`;
    }
    return t;
  };
  let out = '# Dependencies\n\nGenerated by `npm run docs` from package.json and package-lock.json. Do not edit by hand.\n';
  out += '\n## Required (dependencies)\n\nShipped with the app and needed at runtime.\n\n' + table(pkg.dependencies);
  out += '\n## Optional (optionalDependencies)\n\n' + table(pkg.optionalDependencies);
  out += '\n## Development only (devDependencies)\n\nBuild and tooling; not needed at runtime.\n\n' + table(pkg.devDependencies);
  out += `\n## Lockfile\n\n- Direct packages: ${direct.size}\n- Transitive packages: ${transitive} (${total} installed entries in package-lock.json in total)\n`;
  const dups = [...versions.entries()].filter(([, v]) => v.size > 1).sort((a, b) => a[0].localeCompare(b[0]));
  out += '\n## Duplicates (more than one version installed)\n\n';
  if (!dups.length) out += '_None._\n';
  else {
    out += '| Package | Versions |\n| --- | --- |\n';
    for (const [n, v] of dups) out += `| \`${n}\` | ${[...v.keys()].sort().join(', ')} |\n`;
  }
  return out;
}

function writeDocs(root = ROOT) {
  const dir = path.join(root, 'docs');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'architecture.md'), buildArchitecture(root));
  fs.writeFileSync(path.join(dir, 'dependencies.md'), buildDependencies(root));
}

module.exports = { buildArchitecture, buildDependencies, leadingComment, writeDocs };

if (require.main === module) {
  writeDocs();
  console.log('wrote docs/architecture.md and docs/dependencies.md');
}
